version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      biome:
        patterns:
          - "@biomejs/*"
      types:
        patterns:
          - "@types/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "@swc/*"
          - "unplugin-swc"
    ignore:
      - dependency-name: "reflect-metadata"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
