queue_rules:
  - name: dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build-lint-test-publish
      - status-success=security/snyk (iamolegga)

pull_request_rules:
- name: merge pull requests from dependabot if CI passes
  conditions:
    - author~=^dependabot(|-preview)\[bot\]$
    - status-success=build-lint-test-publish
    - status-success=security/snyk (iamolegga)
  actions:
    queue:
      name: dependabot
